name: Deploy API to AWS CloudFormation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and Deploy API
        run: |
          sam build
          sam deploy \
          --stack-name sam-hello-world \
          --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
          --capabilities CAPABILITY_IAM \
          --region ${{ secrets.AWS_REGION }} \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
